extern crate failure;

use failure::Error;

fn main() -> Result<(), Error> {
    unimplemented!()
}
